### ISSUE TITLE
[FEATURE] - Add option for electrostatics color scale value

### ISSUE THREAD

**Issue by nchenche** [i2bc/SURFMAP#16]
## Description

Currently, the electrostatics min/max values are automatically inferred from computed values. This prevents the visual comparison of different maps since their color scale will be different.

## Solution

Add an option to set the min/max values from the command line

**Comment by SuneFjermedal** [comment]
Hi, with a pdb2pqr calculated .pqr file input I have values much higher than eg. 5, can I force the program to not remove everything that is above the set color max values?

**Comment by SuneFjermedal** [comment]
Hi, The issue is because I want to display the surface potential at a specific ph (is this an option that is included in SURFMAP because I have not been able to find it) I use a --pqr with corresponding file and use the argument --color-max-val 5 so I can do this on several ph and compare, however all the values that was calculated above 5 is removed, i.e. no color at all when doing as such. 

see the attachment

best regards

[EEY684_electrostatics_map.pdf](https://github.com/i2bc/SURFMAP/files/14331434/EEY684_electrostatics_map.pdf)

**Comment by nchenche** [comment]
Dear Sune,

In this case, all you have to do is modifiy the value specified as "--color-max-val" so that it corresponds to the maximum OR the minimum value found among all the pqr files you want to compare.

Please let me know if it answered your question,

Best
