### ISSUE TITLE
[Bug]: error in computing electrostatics

### ISSUE THREAD

**Issue by avilella** [i2bc/SURFMAP#22]
### Operating System

Unix (e.g., Ubuntu 20.04)

### Version

2.2.0

### Python Version (optional)

3.10.7

### Python Virtual Environment

Not using a virtual environment

### Execution Environment

Encapsulated environment from the SURFMAP Docker image

### Bug Description

I expected the successful calculation, it gives an error and no output instead.

### Steps to Reproduce

```
surfmap -pdb /bfx_share1/quick_share/alphafold2/outputs/d6/d6472024a556ae23f7ecd8e0b5390ab7/d6472024a556ae23f7ecd8e0b5390ab7.esm.pdb -tomap electrostatics --docker 
```

Error is:
```
SURFACE MAPPING OF THE ELECTROSTATICS PROPERTY
Step 1: computing a shell around the protein surface
Step 2: computing electrostatics potential
Traceback (most recent call last):
  File "/surfmap/.env/bin/surfmap", line 33, in <module>
    sys.exit(load_entry_point('surfmap', 'console_scripts', 'surfmap')())
  File "/surfmap/surfmap/bin/surfmap.py", line 63, in main
    surfmap_local(params=params)
  File "/surfmap/surfmap/bin/surfmap.py", line 18, in surfmap_local
    surfmap_from_pdb(params=params)
  File "/surfmap/surfmap/lib/core.py", line 180, in surfmap_from_pdb
    shell = run_compute_electrostatics(pdb_filename=params.pdbarg, csv_filename=csv_coords, force_field=params.force_field, pqr_filename=params.pqr, out_dir=outdir_elec)
  File "/surfmap/surfmap/tools/compute_electrostatics.py", line 130, in run
    edit_inputgen(inputgen_file=outfile_in, pqrfile=outfile_pqr)
  File "/surfmap/surfmap/tools/compute_electrostatics.py", line 58, in edit_inputgen
    with open(inputgen_file, 'r') as _file :
FileNotFoundError: [Errno 2] No such file or directory: '/home/surfmap/output/tmp-elec/d6472024a556ae23f7ecd8e0b5390ab7.esm.in'
```

### Confirmation

- [X] I confirm I have searched for duplicates and reviewed the relevant documentation.

**Comment by nchenche** [comment]
Hi avilella,

It sounds like the issue is coming from the double extension in your input file: `d6472024a556ae23f7ecd8e0b5390ab7.esm.pdb`.

I have just tried renaming an input file to add it a double extension like you have. From the original file (foo.pdb), electrostatics computation was ok, however with the double extension (foo.esm.pdb) i had the same issue you have encountered.

So to resolve your issue, you'll just have to rename you input file in order to remove the '.esm' part : `d6472024a556ae23f7ecd8e0b5390ab7.pdb`

Sorry for the inconvenience, i am gonna try to fix that bug as soon as possible.

Thank you for using SURFMAP and for highlighting a bug we've never met before.

**Comment by avilella** [comment]
Voila! Problem solved.
